### ISSUE TITLE
Does HTML-KickStart support LESS?

### ISSUE THREAD

**Issue by blachawk** [joshuagatcke/HTML-KickStart#83]
Does HTML-KickStart support LESS? If so, is there any documentation provided for it?

Thanks

**Comment by joshuagatcke** [comment]
There are no LESS files for HTML Kickstart, although it would probably be a pretty easy conversion. 

- Joshua

---------------------------------------------------
Joshua Gatcke
---------------------------------------------------
 <mailto:joshua@99lime.com>joshua@99lime.com <mailto:joshua@99lime.com>
 <http://www.99lime.com/>http://www.99lime.com <http://www.99lime.com/>
1.52.999.910.7350 (Mérida, Mexico)

---------------------------------------------------
Well designed, Handcrafted Websites 
---------------------------------------------------
